Jonnitto:
  GoogleMaps:
    APIKey: AIzaSyA2C5QB8sRiICuBqEEO6RFafW_xa29uc8s
    includeGoogleAPI: true
    includeFunction: true
    includeBackendJS: true
    includeCSS: true
    googleAPI: '//maps.google.com/maps/api/js?key={APIKey}&callback=initJonnittoGoogleMaps'
    cssClasses:
      container: false
      map: jonnitto-googlemaps-mapview
      streetview: jonnitto-googlemaps-streetview
      both:
        wrapper: jonnitto-googlemaps-both-wrapper
        map: jonnitto-googlemaps-both-mapview
        streetview: jonnitto-googlemaps-both-streetview
